/*
 * Splash.java
 *
 * Created on 1 de Agosto de 2006, 18:27
 */

package gui;

/**
 *
 * @author  fernando
 */
public class Splash extends javax.swing.JFrame {
    
    /** Creates new form Splash */
    public Splash() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        status1 = new javax.swing.JLabel();
        status2 = new javax.swing.JLabel();
        menu = new javax.swing.JMenuBar();
        mCadastro = new javax.swing.JMenu();
        mMovimento = new javax.swing.JMenu();
        mAjuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        status1.setText("status");
        status1.setAutoscrolls(true);
        status1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        status2.setAutoscrolls(true);
        status2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        status2.setMaximumSize(new java.awt.Dimension(45, 15));
        status2.setMinimumSize(new java.awt.Dimension(45, 15));
        status2.setPreferredSize(new java.awt.Dimension(45, 15));
        status2.getAccessibleContext().setAccessibleName("");

        mCadastro.setText("Cadastro");
        menu.add(mCadastro);

        mMovimento.setText("Movimenta\u00e7\u00e3o");
        menu.add(mMovimento);

        mAjuda.setText("Ajuda");
        menu.add(mAjuda);

        setJMenuBar(menu);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(status1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 292, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(status2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 138, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap(260, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(status1)
                    .add(status2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 17, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Splash().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu mAjuda;
    private javax.swing.JMenu mCadastro;
    private javax.swing.JMenu mMovimento;
    private javax.swing.JMenuBar menu;
    private javax.swing.JLabel status1;
    private javax.swing.JLabel status2;
    // End of variables declaration//GEN-END:variables
    
}
